shell:
    python manage.py shell 
makemigrations:
    python manage.py makemigrations blog
migrate:
    python manage.py migrate
runserver:
    python manage.py runserver
startapp app:
    python manage.py startapp {{app}}

